Repository greggameplayer/SurvivalNarrativeGame, pull requests merged in 2018-02, with the labels that each got.

#11 add images
  images-fond/fonds/RIPlasereinité.jpg
  images-fond/fonds/arrivée.jpg
  images-fond/fonds/screamer.jpg
  images-fond/fonds/thedescent.jpg
  images-fond/items/LT.png
  images-fond/items/camera.png
  images-fond/items/couteau.png
  images-fond/items/medikit.png
  images-fond/items/pistolet.jpeg
  images-fond/items/sac.png
  images-fond/items/tel.PNG
Labels: review

#12 Add of write animation
  js/functions.js
Labels: review

#13 improve CSS
  styles/style.css
Labels: enhancement, review

#15 Optimization of Functions.js
  js/EventListener.js
  js/functions.js
  styles/style.css
Labels: Optimization, enhancement, review

#14 add a background image
  fonds/RIPlasereinité.jpg
  fonds/arrivee.jpg
  fonds/screamer.jpg
  fonds/thedescent.jpg
  images-fond/fonds/arrivée.jpg
  items/LT.png
  items/camera.png
  items/couteau.png
  items/medikit.png
  items/pistolet.jpeg
  items/sac.png
  items/tel.PNG
  js/functions.js
  styles/style.css
Labels: UI, enhancement, review

#17 add variable for box height
  js/functions.js
  styles/style.css
Labels: enhancement, review
